url: http://brixen.io
permalink: /:categories/:year/:i_month/:i_day/:title
safe: true
lsi: false
source: .
destination: ./public
exclude:
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss
markdown: rdiscount
pygments: false
port: 9876
